### ISSUE TITLE
Plugin for seeing where files are used

### ISSUE THREAD

**Issue by mattjburrows** [nspragg/filehound#17]
I understand this is more of a "grep" feature rather than a file based feature, however with the `addFilter` method we could build up a plugin repository.

The idea is to see where a file / or files are called within a codebase e.g. if file `foo.js` is used in 5 files it should return the 5 files that it is referenced in.

What do you think?

**Comment by nspragg** [comment]
Do you mean something like: 

Const FileHound = require('filehound');
FileHound.plugin(require('uniqFiles'));

const uniqFiles = FileHound
  .create()
  .uniqFiles()
  .find();

**Comment by nspragg** [comment]
or just write a separate npm module
