### ISSUE TITLE
About depth(0) in fileHound.create()

### ISSUE THREAD

**Issue by kevinbird61** [nspragg/filehound#43]
Hello nspragg!
May I ask some question ?
Does there have something like "depth(0)" in using : 
```javascript
var find = FileHound.create()
    .paths(directory)
    .depth(0)
...
```
And get the files in directory ( which is not current directory) ?

**Comment by nspragg** [comment]
Yes. If you want to search for all the files non recursively in a specific directory, use a combination of `.paths` and `depth`. For example:

```js
const Filehound = require('filehound');

const myDir = "/tmp";
const results = Filehound.create()
    .paths(myDir)
    .depth(0) // non recursive search only 
    .find()

results.each(console.log); 
```

**Comment by kevinbird61** [comment]
Thanks a lot!

**Comment by nspragg** [comment]
@kevinbird61 happy to help. If you have any further questions, just let me know.
