### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by lgodard** [nspragg/filehound#47]
Hi,
The FileHound module seems great and i'll test it for my project.
Is there any Licence information somewhere ?
Thanks in advance
Laurent

**Comment by nspragg** [comment]
Hi Laurent, 

I've added a MIT license: 
https://github.com/nspragg/filehound/blob/master/LICENSE.txt

Hope you find FileHound useful. 
Nick

**Comment by lgodard** [comment]
Thanks a lot for the license and FileHound that is a great tool :)
