### ISSUE TITLE
depth doesn't work if path starts with "./"

### ISSUE THREAD

**Issue by pvarenik** [nspragg/filehound#48]
Working code:
`var reportFiles = FileHound.create()
            .paths('reports')
            .ext('MD')
            .not()            
            .depth(0)
            .find();`

Not working code:
`var reportFiles = FileHound.create()
            .paths('./reports')
            .ext('MD')
            .not()            
            .depth(0)
            .find();`
Code above returns all files, including subfolders.

**Comment by nspragg** [comment]
@pvarenik thanks for raising this issue. I'll investigate this within the next couple of days. Thanks again.

**Comment by nspragg** [comment]
fixes #43
