### ISSUE TITLE
Incorrect working of depth with subfolders in paths

### ISSUE THREAD

**Issue by pvarenik** [nspragg/filehound#49]
E.g.:
FileHound.create()
.paths( './screens', './screens/actual', './screens/diff')
            .ext('MD')
            .not()
            .depth(0)
            .find()
            .then(function (files) {
                for (var i = 0; i < files.length; i++) {
                    fs.unlink(files[i]);
                    console.log('DELETE: ', files[i]);
                };
            });
Formatted code: https://gist.github.com/pvarenik/26e5270a546407c7e8341c159a902903
This code doesn't delete files in  './screens/actual' and './screens/diff'

**Comment by nspragg** [comment]
Thanks for raising this issue. I will investigate within the next 48 hours.

**Comment by nspragg** [comment]
Fixed in 1.13.1
