### ISSUE TITLE
Implement .depth

### ISSUE THREAD

**Issue by nspragg** [nspragg/filehound#5]
Add support to specify the level of recursion i.e .depth. 

```javascript 
const query = FileHound.create()
        .paths('/some/path')
        .depth(3)
        .find();
```

.depth(0) should only search the current dir (turn recursion off). 

Draft implementation:
https://github.com/nspragg/filehound/tree/withDepth

**Comment by cejast** [comment]
It seems like the `withDepth` branch has already implemented this all fine. Is there anything else in particular you were looking for here?
