### ISSUE TITLE
[Q] UNC paths supported?

### ISSUE THREAD

**Issue by samuelstein** [nspragg/filehound#58]
Hello guys,
could it be possible that the great filehound paths() method doesn't support windows unc paths?

**Comment by nspragg** [comment]
@samuelstein - thanks for raising this issue. You're correct, seems like there is an issue with windows UNC paths. Should do a patch release within the next 48 hours.

**Comment by nspragg** [comment]
@samuelstein - are you getting a particularly error?

**Comment by nspragg** [comment]
@samuelstein - will be fixed in 1.14.2

**Comment by nspragg** [comment]
Replicated issue on win32 and patched in v1.14.2

@samuelstein - let me know if you're still having issues. Thanks.

**Comment by samuelstein** [comment]
it's working now. thanks
