### ISSUE TITLE
exclude

### ISSUE THREAD

**Issue by serg94** [nspragg/filehound#61]
Hello. does it have exclude option? E.g. I want to get all *.js files but not *.spec.js files

**Comment by nspragg** [comment]
There is a `.discard` method. You should be able to use this in combination with `.ext` to find .js files but exclude .spec.js files. For example:

```js
const filehound = FileHound.create();
filehound
    .ext('js')
    .discard(".*spec.js")
    .find()
    .each(console.log); // print results 
```
