### ISSUE TITLE
discard - root path

### ISSUE THREAD

**Issue by dvdciri** [nspragg/filehound#69]
### Description
It seems like File Hound doesn't work properly on CI, i'm just executing this code below and it returns an empty array of files, while locally the same code returns many different files:
```
const files = await FileHound
    .create()
    .paths(projectRootPath)
    .discard("build")		
    .depth(20)
    .ignoreHiddenDirectories()
    .ignoreHiddenFiles()
    .ext('.java', '.kt')
    .find();
```
The js code is here: https://github.com/dvdciri/daggraph/blob/feature/fix-skipped-tests/src/dagger/DaggerAnalyzer.js#L16
### Expected behaviour
Correct files returned

### Actual behaviour
Empty array of files

### Steps to reproduce
Run the snipped on CI
Have a look here https://travis-ci.org/dvdciri/daggraph/jobs/325764397#L485 ("File hound files: ")
While locally i get this:
```
File hound files: /Users/dci03/Projects/Personal/daggraph/test/data/kotlin_dagger_default/app/src/androidTest/java/org/loop/example/ApplicationTest.java,/Us
ers/dci03/Projects/Personal/daggraph/test/data/kotlin_dagger_default/app/src/main/java/org/loop/example/AndroidModule.kt,/Users/dci03/Projects/Personal/dagg
raph/test/data/kotlin_dagger_default/app/src/main/java/org/loop/example/ApplicationComponent.kt,/Users/dci03/Projects/Personal/daggraph/test/data/kotlin_dag
ger_default/app/src/main/java/org/loop/example/ForApplication.kt,/Users/dci03/Projects/Personal/daggraph/test/data/kotlin_dagger_default/app/src/main/java/o
rg/loop/example/MainActivity.kt,/Users/dci03/Projects/Personal/daggraph/test/data/kotlin_dagger_default/app/src/main/java/org/loop/example/MyApplication.kt
```
### Operating system
Mac

**Comment by nspragg** [comment]
This _may_ be failing on CI because the project root on the remote machine contains "**build**". Therefore, `.discard("build")`, is filtering all results as each path on CI contains the string "build". 

Note, on your local machine, you don't have "build" in the project path.

**Comment by dvdciri** [comment]
Shouldn't it discard the folder starting from the path that you are analyzing and going deeper and not before the actual folder? 
I.e. a/build/folder/path, if path contains any folders with the name build then it would discard them but not discard the whole thing?

**Comment by nspragg** [comment]
The current implementation of `.discard` considers the full path. The behaviour you've described is a new requirement, which I'll consider for V2. This is currently in progress (don't have a release date yet). 

In the meantime, I suggest modifying the discard pattern to be more specific.

**Comment by dvdciri** [comment]
Cool perfect. I'll leave this with you, thanks
