### ISSUE TITLE
Special Characters in .match() / .glob()

### ISSUE THREAD

**Issue by whiteco** [nspragg/filehound#73]
### Description
Each file in my directory has a 'set name' appended to it: i.e.  'Card [XYZ].jpg'. 
When using a string that contains special characters in .glob() or .match(), results are not as expected.

### Expected behaviour
stringToSearch = "Card*[XYZ]"
.glob("*"+stringToSearch+"*")

Should find results of "Card [XYZ].jpg", "Card Two [XYZ].jpg", etc.

### Actual behaviour
Instead, am getting zero results. However, setting stringToSearch = "Card*[XYZ" works perfectly fine. Changed naming convention to ( ) instead of [ ] and am getting same issues.

### Steps to reproduce
Have special characters in filename and a special character as the last character of the string being used in .glob() / .match().

### Operating system
Windows 10 Pro x64

**Comment by nspragg** [comment]
Hi @whiteco. Can you provide the exact `filehound` call you are making?
