### ISSUE TITLE
Sort results

### ISSUE THREAD

**Issue by kellerkichel** [nspragg/filehound#76]
Is there any way to sort the results? like for creation time or last modified?

**Comment by nspragg** [comment]
@kellerkichel - it's not the responsibility of `Filehound` to do the sorting. However, processing the results with `fs` and `lodash` is one solution. 

For example, the following code performs a non-recursive search (`.depth(0))` for files in `/tmp` and prints the results by most recent (creatation time):

```js
const _ = require('lodash');
const fs = require('fs')
const filehound = require('filehound');

function toObject(files) {
  return files.map((file) => {
    return {
      name: file,
      time: fs.statSync(file).birthtimeMs
    }
  });
}

async function main() {
  const files = await filehound.create()
    .path("/tmp")
    .depth(0)
    .find();

 const mostRecent = _(toObject(files))
    .orderBy('time', 'desc')
    .map('name')
    .value();

  console.log(mostRecent);
}

main();
```

**Comment by kellerkichel** [comment]
@nspragg thanks... help a lot 😄
