### ISSUE TITLE
Follow symbolic links 

### ISSUE THREAD

**Issue by nspragg** [nspragg/filehound#77]
Add support for following symbolic links to files.

**Comment by gautaz** [comment]
Hello @nspragg, it seems like this feature has been added since.

Is there actually a way to disable this behavior?

**Comment by nspragg** [comment]
@gautaz - This feature has not been implemented. Here is a test to demonstrate it's not following symbolic links:

Test code:
`const FileHound = require('filehound');

const files = FileHound.create()
  .paths('./test-links')
  .ext('json')
  .find();

files.then(console.log);`

The results:
`➜  ~ ll test-links
total 0
-rw-r--r--  1 my_user  staff     0B 23 Apr 17:40 a.json
-rw-r--r--  1 my_user  staff     0B 23 Apr 17:40 b.json
-rw-r--r--  1 my_user  staff     0B 23 Apr 17:40 c.json
lrwxr-xr-x  1 my_user  staff    11B 23 Apr 17:41 link_to_json_file -> /tmp/d.json
➜  ~ node test-link.js
[ 'test-links/a.json', 'test-links/b.json', 'test-links/c.json' ]`

**Comment by gautaz** [comment]
@nspragg Ok, I have been misled by the description of your issue, what I am referring to is finding matches recursively by following symbolic links to folders.

For instance:

```javascript
  const findGlobNotInNodeModules = await FileHound.create()
    .path('.')
    .ext('json')
    .find();
```

Would match twice the file `a.json` in this case:

```
❯ ls -lR .
.:
total 4
drwxr-xr-x 1 user users 12 Apr 23 19:16 a
lrwxrwxrwx 1 user users  1 Apr 23 19:16 b -> a

./a:
total 0
-rw-r--r-- 1 user users 0 Apr 23 19:16 a.json
```

Is there a way to avoid this behavior?

**Comment by nspragg** [comment]
You could try using a custom filter:
https://nspragg.github.io/filehound/FileHound.html#addFilter

For example:
```js
const FileHound = require('filehound');
const path = require('path');
const fs = require('fs');

function isNotSymLinkToDir(file) {
  return !fs.lstatSync(path.dirname(file.getName())).isSymbolicLink();
}

async function main() {
 const files = await FileHound.create()
  .paths('./test-links')
  .addFilter(isNotSymLinkToDir)
  .ext('json')
  .find();

  console.log(files);
}

main();
```

**Comment by nspragg** [comment]
No demand for this feature at present. Happy to reopen if required.
