### ISSUE TITLE
Return file names?

### ISSUE THREAD

**Issue by goldingdamien** [nspragg/filehound#78]
Any chance of adding way to return filenames or file objects?
https://github.com/nspragg/filehound/issues/64

something like below:
`.returns('filename') // 'path' - default, filename, file.`

I understand the desire to keep things simple, but this library provides more than just file names due to the chaining mechanism which could be applied to more situations.

Regards.

**Comment by nspragg** [comment]
@goldingdamien - thanks for raising this. It would be good to drill down into some more detail. 

Can you provide some example situations/scenarios you had in mind? 

If the library could be configured to return `file objects`, which object would you expect? It uses an internal representation of a file internally (`file-js`). Or maybe a custom object? i.e just containing basic file stat info?

**Comment by goldingdamien** [comment]
Basic file info is probably best as I think many people would expect or be more familiar with it.
The main issue is that this library filters out files and provides only the paths.
I have not seen the internal code, but I assume it works with file objects so I assume that it should be simple with little negative effect to be able to return the filtered data by files instead of a subset(paths) of the files.
Personally, I was using for paths then realized I had another situation where I need file stat info. Ideally, it should of been a little config tweak to get files instead.
Regards.

**Comment by goldingdamien** [comment]
Yes, the stats would be great, thanks.

**Comment by nspragg** [comment]
@goldingdamien  - support added for including file stats in v1.17.0
