### ISSUE TITLE
issue with grunt

### ISSUE THREAD

**Issue by josephkuruvilla** [nspragg/filehound#80]
When i run with node its perfectly working. But its not working with grunt. Please help us.
![Screen Shot 2019-03-21 at 22 39 06](https://user-images.githubusercontent.com/18065815/54770902-30a57d00-4c2a-11e9-9534-02fc5eec7acb.png)

**Comment by nspragg** [comment]
@josephkuruvilla - what is the problem specifically? Are you getting on error(s)? Unexpected results? 

I will try to assist you, but you need to provide more information.

**Comment by josephkuruvilla** [comment]
HI @nspragg ,
I am trying to get all the folder names in the build folder. I have created thumbs.js file and i have attached the above screenshot. My project folder structure is projects/demo/dist/build. I am running the project in the demo directory. When i run with node its working Cool. I am automating the task using Grunt.  I have registered this task using grunt. 

My project structure
![Screen Shot 2019-03-22 at 15 02 04](https://user-images.githubusercontent.com/18065815/54813427-82461a00-4cb3-11e9-8bdd-400a62ee34e6.png)

Grunt task structure: 
![Screen-Shot-2019-03-22-at-15 04 28](https://user-images.githubusercontent.com/18065815/54813681-1d3ef400-4cb4-11e9-90fe-a314667bc2b5.png)

When i am trying to accessing the path using grunt task **Users/meiyap/Desktop/up-tool/up-dev-tool-fw/projects/demo/dist/build**. I am not able to get into this and i am not getting any errors also.

Please do the needful

**Comment by nspragg** [comment]
I can't comment on grunt specifically, but as far as `filehound` is concerned:

1. Are you sure the `path` exists at the time you execute filehound? 
2. If so, is the path a link? 
3. Are you sure `.html` extensions actually exist at that path?

**Comment by josephkuruvilla** [comment]
Are you sure the path exists at the time you execute filehound?
Its Existing.
![Screen Shot 2019-03-22 at 16 19 05](https://user-images.githubusercontent.com/18065815/54818033-554b3480-4cbe-11e9-8b35-33cfd12e4831.png)

If so, is the path a link?
Users/meiyap/Desktop/up-tool/up-dev-tool-fw/projects/demo/dist/build. this is the path link. can i mentioned like this?
Yes this is the path link.
Are you sure .html extensions actually exist at that path?
Yes html files are there.

**Comment by nspragg** [comment]
by link, I mean a symbolic link. **If** the path is a **symbolic link**, filehound will ignore it. Support for following symbolic links will be added in a future release.

**Comment by josephkuruvilla** [comment]
Oops.. Thanks for ur valuable time. Have a great day

**Comment by nspragg** [comment]
You can follow this #77 

PRs are welcome.
