### ISSUE TITLE
 FileHound.create() no longer works in latests release

### ISSUE THREAD

**Issue by cekvenich** [nspragg/filehound#83]
FileHound.create() no longer works. in .1. I have to roll back.

**Comment by nspragg** [comment]
@cekvenich - what error are you seeing? Are you referring to a TS definition error or runtime error? 

At run time, `create` successfully creates an instance, which executes a search. 

Tested using:
```
const FileHound = require('filehound');

async function main() {
  const files = await FileHound.create()
  .ext('json')
  .find();

  console.log(files); 
}
main();
```js

**Comment by cekvenich** [comment]
In .1 at compile time: FileHound.create() does not exist. 
I have used older version just fine. .0 
( here https://github.com/metabake/mbCLI/tree/master/src )

**Comment by nspragg** [comment]
@cekvenich - the problem has been reproduced. I've issued a patch in `1.17.2`. Does this work for you?

**Comment by cekvenich** [comment]
Thank you for trying. Not fixed yet:
https://nspragg.github.io/filehound/FileHound.html#addFilter
I have addFilter(function) in my code.
w/ .2 I get:
error TS2345: Argument of type '(fn: any) => boolean' is not assignable to parameter of type '() => boolean'.

So I am reverting again back to .0

**Comment by nspragg** [comment]
@cekvenich  - Sorry about that! The TS definition has been retrofitted manually, which can be a little error prone. I'm hoping to do a V2 (TS) release in the near future. 

Anyway, I've patched `addFilter` in `1.17.3`.

**Comment by cekvenich** [comment]
Works. I'm now on latest version. Thanks for maintaining the package!

**Comment by nspragg** [comment]
@cekvenich - Great stuff. Happy to help out :-)
