### ISSUE TITLE
match() and glob() have different behavior

### ISSUE THREAD

**Issue by marcobusemann** [nspragg/filehound#88]
The documentation states that ```glob()``` and ```match()``` have the same functionality:
![image](https://user-images.githubusercontent.com/13619853/85828763-68826500-b789-11ea-8845-f6b1c0bff252.png)

But actually that is not true. The source code shows that ```match()``` only uses one argument. The method ```glob()```instead uses all arguments. Therefore the example ```.glob('*tmp1*','*tmp2*')```does not work with ```match()```.

Is this intentional?

**Comment by nspragg** [comment]
@marcobusemann - No, it's a mistake in the documentation.

**Comment by marcobusemann** [comment]
Ok thanks, i will add a pull-request in a few days.
