### ISSUE TITLE
Feature request .sort()

### ISSUE THREAD

**Issue by abakermi** [nspragg/filehound#89]
### Is your proposal related to a problem?

no

### Describe the solution you'd like

```
const FileHound = require('filehound');

const files = FileHound.create()
  .paths('/some/dir')
  .find()
  .sort({modified:1})  // could be other 
```

### Additional context

`.sort()` invoked after find

**Comment by nspragg** [comment]
@abakermi - thanks for raising this. 

This library is focused on finding files. Sorting the results would be the responsibility of the user, either directly in JavaScript or using a utility library like `lodash`.
